version: "3"
services:
  mysql:
    image: mysql/mysql-server:5.6
    env_file:
      - docker-mysql/docker-mysql-server-conf

    volumes:
      - mysqldb:/var/lib/mysql

  stock_project:
    build: .
    image: stock_project
#    command: sh docker-entrypoint.sh
    volumes:
      - static:/static/
    environment:
      - STOCK_PROJECT_MACHINE_TYPE=dev
      - STATIC_ROOT=/static/
      - DOCKER_ENV=true

    depends_on:
      - mysql
  nginx:
    build: docker-nginx
    image: nginx_stock_project
    ports:
      - "80:80"
    depends_on:
      - stock_project
    volumes:
      - static:/static

volumes:
  static:
  mysqldb: