# Generated by Django 3.1.1 on 2020-11-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201027_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='WatchStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stock')),
            ],
        ),
    ]
