# Generated by Django 3.1.1 on 2020-11-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201115_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('expense_price', models.PositiveIntegerField()),
                ('budget_left', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SellStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('earning_price', models.PositiveIntegerField()),
                ('budget_left', models.IntegerField()),
                ('bought_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_stock', to='myapp.buystock')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_stocks', to='myapp.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='buystock',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_stocks', to='myapp.portfolio'),
        ),
        migrations.AddField(
            model_name='buystock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stock'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.portfolio'),
        ),
    ]
