# Generated by Django 3.1.1 on 2020-11-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201114_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='change_status',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='change_threshold',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='price_threshold',
        ),
        migrations.AddField(
            model_name='activity',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='myapp.rules'),
        ),
        migrations.AddField(
            model_name='changestatus',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_statuses', to='myapp.rules'),
        ),
        migrations.AddField(
            model_name='changethreshold',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_thresholds', to='myapp.rules'),
        ),
        migrations.AddField(
            model_name='pricethreshold',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_thresholds', to='myapp.rules'),
        ),
    ]
