# Generated by Django 3.1.1 on 2020-11-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201123_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtstock',
            name='threshold',
            field=models.FloatField(null=True),
        ),
    ]
