# Generated by Django 3.1.1 on 2020-11-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_boughtstock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='primary_exchange',
        ),
    ]
