# Generated by Django 3.1.1 on 2020-11-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201115_1228'),
        ('myapp', '0008_auto_20201114_2036'),
        ('myapp', '0008_auto_20201114_1533'),
    ]

    operations = [
    ]
