# Generated by Django 3.1.1 on 2020-11-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_merge_20201115_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedStockRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='watchstock',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='watchstock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='changestatus',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='changethreshold',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='pricethreshold',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notification_rules',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.DeleteModel(
            name='WatchStock',
        ),
        migrations.AddField(
            model_name='watchedstockrule',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watched_stock_rule', to='myapp.activity'),
        ),
        migrations.AddField(
            model_name='watchedstockrule',
            name='change_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watched_stock_rule', to='myapp.changestatus'),
        ),
        migrations.AddField(
            model_name='watchedstockrule',
            name='change_threshold',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watched_stock_rule', to='myapp.changethreshold'),
        ),
        migrations.AddField(
            model_name='watchedstockrule',
            name='price_threshold',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watched_stock_rule', to='myapp.pricethreshold'),
        ),
        migrations.AddField(
            model_name='watchedstock',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AddField(
            model_name='watchedstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stock'),
        ),
        migrations.AddField(
            model_name='watchedstock',
            name='watched_stock_rule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_stock', to='myapp.watchedstockrule'),
        ),
    ]
