# Generated by Django 3.1.1 on 2020-11-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201115_1228'),
        ('myapp', '0009_notification_is_read'),
    ]

    operations = [
    ]
