# Generated by Django 3.1.1 on 2020-11-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_notification_is_read'),
        ('myapp', '0006_auto_20201115_1228'),
    ]

    operations = [
    ]
