# Generated by Django 3.1.1 on 2020-11-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201115_1521'),
        ('myapp', '0009_notification_is_read'),
    ]

    operations = [
    ]
