# Generated by Django 3.1.1 on 2020-11-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_merge_20201115_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationAnalyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='watchedstockrule',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='watchedstockrule',
            name='change_status',
        ),
        migrations.RemoveField(
            model_name='watchedstockrule',
            name='change_threshold',
        ),
        migrations.RemoveField(
            model_name='watchedstockrule',
            name='price_threshold',
        ),
        migrations.RemoveField(
            model_name='watchedstock',
            name='watched_stock_rule',
        ),
        migrations.AddField(
            model_name='changestatus',
            name='num_of_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='changestatus',
            name='status',
            field=models.CharField(choices=[('N', 'Negative'), ('P', 'Positive')], default='P', max_length=10),
        ),
        migrations.AddField(
            model_name='changestatus',
            name='watched_stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='change_status_rules', to='myapp.watchedstock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changethreshold',
            name='watched_stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='change_threshold_rules', to='myapp.watchedstock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricethreshold',
            name='watched_stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='price_threshold_rules', to='myapp.watchedstock'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='WatchedStockRule',
        ),
        migrations.AddField(
            model_name='recommendationanalyst',
            name='watched_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_analyst_rules', to='myapp.watchedstock'),
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='watched_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_period_rules', to='myapp.watchedstock'),
        ),
    ]
