# Generated by Django 3.1.1 on 2020-11-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_merge_20201117_1547'),
        ('myapp', '0011_merge_20201115_2020'),
    ]

    operations = [
    ]
