# Generated by Django 3.1.1 on 2020-11-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201115_2239'),
        ('myapp', '0010_merge_20201117_1547'),
    ]

    operations = [
    ]
