# Generated by Django 3.1.1 on 2020-11-16 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201115_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeStatusRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'Negative'), ('P', 'Positive')], default='P', max_length=10)),
                ('num_of_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(2)])),
                ('watched_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_status_rules', to='myapp.watchedstock')),
            ],
        ),
        migrations.RenameModel(
            old_name='ActivityPeriod',
            new_name='ActivityPeriodRule',
        ),
        migrations.RenameModel(
            old_name='ChangeThreshold',
            new_name='ChangeThresholdRule',
        ),
        migrations.RenameModel(
            old_name='PriceThreshold',
            new_name='PriceThresholdRule',
        ),
        migrations.RenameModel(
            old_name='RecommendationAnalyst',
            new_name='RecommendationAnalystRule',
        ),
        migrations.DeleteModel(
            name='ChangeStatus',
        ),
    ]
