# Generated by Django 3.1.1 on 2020-11-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20201117_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityPeriodRule',
        ),
    ]
