# Generated by Django 3.1.1 on 2020-11-18 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20201118_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationanalystrule',
            name='recommenders_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
