# Generated by Django 3.1.1 on 2020-11-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_recommendationanalystrule_recommenders_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendationanalystrule',
            old_name='recommenders_percentage',
            new_name='threshold_recommenders_percentage',
        ),
    ]
