# Generated by Django 3.1.1 on 2020-11-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20201118_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricethresholdrule',
            name='price_threshold',
            field=models.FloatField(default=0),
        ),
    ]
