# Generated by Django 3.1.1 on 2020-11-22 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20201118_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationanalystrule',
            name='threshold_recommenders_percentage',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
